export { default as Home } from "./home/Home";
export { default as About } from "./about/About";
export { default as Work } from "./mywork/Work";
export { default as PuntDec } from "./mywork/workDec/PuntDec";
export { default as SignatureDec } from "./mywork/workDec/SignatureDec";
export { default as PeriDec } from "./mywork/workDec/PeriDec";
export { default as RugDec } from "./mywork/workDec/RugDec";
export { default as CaddieDec } from "./mywork/workDec/CaddieDec";
export { default as SurenDec} from "./mywork/workDec/SurenDec";
export { default as SmartaDec} from "./mywork/workDec/SmartaDec";
export { default as AIBotDec} from "./mywork/workDec/AIBotDec";
